---
# tasks file for win_ad_install
- name: Install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: yes
    include_sub_features: yes

- name: Create new domain in a new forest on the target host
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: ad_controllers

- name: Reboot AD controller
  win_reboot:
    test_command: "nltest /dclist:{{ ad_domain_name }}"
  when: ad_controllers.reboot_required
  register: domain_list

- name: Debug domain_list
  debug:
   var: domain_list

#- name: Configure AD users
#  include_tasks: ad_users.yml
